---
- name: Installs Graylog .deb repo
  apt:
    deb: "https://packages.graylog2.org/repo/packages/graylog-{{ graylog_version }}-repository_latest.deb"
  become: yes

- name: Installs Graylog Enterprise
  apt:
    name:
      - graylog-server
      - graylog-enterprise-plugins
      - graylog-integrations-plugins
      - graylog-enterprise-integrations-plugins
    state: present
    update_cache: yes
  become: yes

- name: Add Graylog server.conf
  become: yes
  template:
    src: templates/server.conf.j2
    dest: /etc/graylog/server/server.conf
    group: root
    owner: graylog
    mode: u=rw,g=r,o=
  notify: Restarts Graylog-Server Service

- name: Ensures Graylog has started
  systemd:
    name: graylog-server
    daemon_reload: yes
    enabled: yes
    state: started
  become: yes